---

- name: create cloudformation template folder
  file:
    path: roles/deploy.aws/files/cloudformation
    state: directory

- name: generate cloudformation templates
  template:
    src: "{{ item }}"
    dest: "roles/deploy.aws/files/cloudformation/{{ item | replace('.j2', '')}}"
  with_items:
  - main_template.yml.j2
  - security_groups_template.yml.j2
  - vpc_template.yml.j2
  - messageapp_template.yml.j2
  - route53_template.yml.j2
  - rds_template.yml.j2
