apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - env:
        - name: demo_database_host
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_host
        - name: demo_database_name
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_name
        - name: demo_database_password
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_password
        - name: demo_database_port
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_port
        - name: demo_database_username
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_user
        - name: logging_level_com_message
          value: DEBUG
        - name: spring_jpa_hibernate_ddlauto
          value: none
        - name: spring_profiles_active
          value: test
        image: demo/message-service:1.0-SNAPSHOT
        name: message-service
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      restartPolicy: Always
