kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    volume: db-volume
  name: database-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/db-postgres

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: db-volume