version: '3.1'

services:

  message-service:
    image: demo/message-service:1.0-SNAPSHOT
    ports:
      - "80:8080"
    environment:
      spring_jpa_hibernate_ddlauto: none
      spring_profiles_active: test
      demo_database_name: demo
      demo_database_host: postgres
      demo_database_port: 5432
      demo_database_username: messageservice
      demo_database_password: secretpassword
      logging_level_com_message: DEBUG
    restart: always
    depends_on:
      - postgres
    networks:
      - demo-net

  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: messageservice
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: demo
    healthcheck:
      test: pg_isready -U messageservice -d demo
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - demo-net

volumes:
  db-volume:

networks:
  demo-net: